# -*- coding: utf-8 -*-
"""simple reflex vacumn agent.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kunk00-w20u1DyibFJyjtPSNorQ9tKr6
"""



import random

"""STEP 1: SET UP THE ENVIRONMENT"""

environment = {
    'A': random.choice(['Clean', 'Dirty']),
    'B': random.choice(['Clean', 'Dirty'])
}

"""### Place the agent randomly in location A or B"""

agent_location = random.choice(['A', 'B'])

"""### This variable will count how many locations the agent cleans"""

performance_score = 0

"""###STEP 2: DISPLAY THE INITIAL STATE"""

print("=" * 45)
print("       SIMPLE REFLEX VACUUM AGENT")
print("=" * 45)
print("\n--- INITIAL ENVIRONMENT STATE ---")
print(f"  Location A : {environment['A']}")
print(f"  Location B : {environment['B']}")
print(f"  Agent starts at : Location {agent_location}")
print("-" * 45)
print("\n--- AGENT ACTIONS ---")

""" #### The agent will visit exactly 2 locations (A then B, or B then A) /We loop twice: once for the starting location, once for the other"""

for step in range(2):

    print(f"\nStep {step + 1}: Agent is at Location {agent_location}")

    current_condition = environment[agent_location]
    print(f"  Sensing... Location {agent_location} is '{current_condition}'")

"""#####-\ ACT: Apply the reflex rule"""

if current_condition == 'Dirty':
    environment[agent_location] = 'Clean'
    performance_score += 1
    print(f"  Action: CLEAN Location {agent_location}")
    print(f"  Result: Location {agent_location} is now 'Clean' ✓")
else:
    print(f"  Action: NO CLEAN needed (already Clean)")

# Move agent after step 0
if step == 0:
    if agent_location == 'A':
        agent_location = 'B'
    else:
        agent_location = 'A'
    print(f"  Action: MOVE to Location {agent_location}")

"""#####STEP 4: DISPLAY THE FINAL STATE AND PERFORMANCE SCORE"""

print("\n" + "=" * 45)
print("--- FINAL ENVIRONMENT STATE ---")
print(f"  Location A : {environment['A']}")
print(f"  Location B : {environment['B']}")
print("-" * 45)

"""###### Calculate and display the performance score"""

print(f"\n--- PERFORMANCE SCORE ---")
print(f"  Locations cleaned : {performance_score} out of 2")

"""###### Give a message based on how many locations were cleaned"""

if performance_score == 2:
    print("  Result : EXCELLENT! Agent cleaned both locations! 🌟")
elif performance_score == 1:
    print("  Result : GOOD. Agent cleaned 1 dirty location.")
else:
    print("  Result : Both locations were already clean. Nothing to do!")

print("=" * 45)